### ISSUE TITLE
Building from top level streamsx.watsonexplorer does not seem to build anything

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.watsonexplorer#6]
I ran `gradle build` from streamsx.watsonexplorer.  While the build was successful, it does not seem to build the actual toolkit.  

I had to go into com.ibm.streamsx.watsonexplorer for the build to get kicked off.

**Comment by cancilla** [comment]
This has been fixed. Running `gradle build` from top-level directory will build the toolkit.
